name = "etf-campus"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "ETF_PRICES"
database_name = "etf-prices"
database_id = "11c4e874-fba2-4e34-91d0-808892284c86"

[env.preview.vars]
SUPABASE_URL = "https://vdjyuqtcqhchopbrhexd.supabase.co"

[[env.preview.d1_databases]]
binding = "ETF_PRICES"
database_name = "etf-prices"
database_id = "11c4e874-fba2-4e34-91d0-808892284c86"
