export declare function encodeBase64Url(str: string): string;
export declare function decodeBase64Url(str: string): string;
export declare function sessionHeaders(session: { access_token: string; refresh_token: string }, csrfToken?: string, rememberMe?: boolean): Headers;
export declare function clearSessionHeaders(): Headers;
export declare function passwordSetupHeaders(session: { access_token?: string }, options: { rememberMe?: boolean; csrfToken?: string }): Headers;
export declare function readPasswordSetup(request: Request): { accessToken: string; rememberMe: boolean } | null;
export declare function clearPasswordSetupHeaders(): Headers;
export declare function mergeSessionHeaders(response: Response, session: { headers: Headers; cookies?: string[] }): Response;
export declare function clearSessionResponse(response: Response): Response;
export declare function requestCsrfToken(request: Request): string;
export declare function enforceCsrf(context: any): Response | null;
export declare function requestSessionTokens(request: Request): { accessToken: string; refreshToken: string; rememberMe: boolean };
export declare function authenticatedSession(context: any): Promise<any>;
export declare const COMMUNITY_SESSION_COOKIE_NAMES: Record<string, string>;
