import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { parse } from "csv-parse/sync";

const DEFAULT_INPUT = "data/etf_master_draft.csv";
const DEFAULT_OUTPUT = ".tmp/market_briefing_universe_seed.sql";
const INSERT_BATCH_SIZE = 200;

function argument(name, fallback) {
  const index = process.argv.indexOf(name);
  return index >= 0 && process.argv[index + 1] ? process.argv[index + 1] : fallback;
}

function sqlText(value) {
  if (value === null || value === undefined || value === "") return "NULL";
  return `'${String(value).replaceAll("'", "''")}'`;
}

function numericOrNull(value) {
  const normalized = String(value ?? "").replaceAll(",", "").trim();
  if (!normalized) return null;
  const parsed = Number(normalized);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : null;
}

function normalizeRiskType(value) {
  const normalized = String(value ?? "").trim().toLowerCase();
  const riskMap = {
    normal: "normal",
    leverage: "leveraged",
    leveraged: "leveraged",
    inverse: "inverse",
  };
  return riskMap[normalized] ?? "unknown";
}

function isTicker(value) {
  return /^[A-Z0-9]{6}$/.test(String(value ?? "").trim().toUpperCase());
}

function chunks(values, size) {
  const output = [];
  for (let offset = 0; offset < values.length; offset += size) output.push(values.slice(offset, offset + size));
  return output;
}

const inputPath = resolve(argument("--input", DEFAULT_INPUT));
const outputPath = resolve(argument("--output", DEFAULT_OUTPUT));
const sourceLabel = argument("--source-label", "etf_master_draft");

const rawCsv = await readFile(inputPath, "utf8");
const rawRows = parse(rawCsv, { columns: true, skip_empty_lines: true, bom: true, trim: true });
const byTicker = new Map();
const skippedTickers = [];

for (const row of rawRows) {
  const ticker = String(row.ticker ?? "").trim().toUpperCase();
  if (!isTicker(ticker)) {
    skippedTickers.push(ticker || "<empty>");
    continue;
  }
  const etfName = String(row.name ?? "").trim();
  if (!etfName) throw new Error(`ETF name is empty for ticker ${ticker}`);
  byTicker.set(ticker, {
    ticker,
    etfName,
    riskType: normalizeRiskType(row.risk_type),
    assetClass: String(row.asset_class ?? "").trim() || null,
    aumValue: numericOrNull(row.aum),
    asOfDate: String(row.bas_dt ?? "").trim(),
  });
}

const universe = [...byTicker.values()].sort((left, right) => left.ticker.localeCompare(right.ticker));
if (!universe.length) throw new Error("No valid six-character KRX ETF codes were found in the master CSV.");
const asOfDates = [...new Set(universe.map((row) => row.asOfDate))];
if (asOfDates.length !== 1 || !/^\d{8}$/.test(asOfDates[0])) {
  throw new Error(`Expected exactly one YYYYMMDD master date, received: ${asOfDates.join(", ") || "<empty>"}`);
}
const sourceVersion = `${sourceLabel}:${asOfDates[0]}`;

const statements = [
  "-- Generated by scripts/generate_market_briefing_universe_seed.mjs. Do not edit manually.",
  `-- Source: ${inputPath}`,
  `-- Source version: ${sourceVersion}`,
  "-- Cloudflare D1 applies uploaded SQL atomically; do not add BEGIN/COMMIT.",
];

for (const batch of chunks(universe, INSERT_BATCH_SIZE)) {
  const values = batch.map((row) => `(${sqlText(row.ticker)}, ${sqlText(row.etfName)}, ${sqlText(row.riskType)}, ${sqlText(row.assetClass)}, ${row.aumValue ?? "NULL"}, 1, ${sqlText(sourceVersion)}, CURRENT_TIMESTAMP)`).join(",\n  ");
  statements.push(
    "INSERT INTO etf_universe_current (ticker, etf_name, risk_type, asset_class, aum_value, is_active, source_version, updated_at) VALUES",
    `  ${values}`,
    "ON CONFLICT(ticker) DO UPDATE SET",
    "  etf_name=excluded.etf_name, risk_type=excluded.risk_type, asset_class=excluded.asset_class,",
    "  aum_value=excluded.aum_value, is_active=1, source_version=excluded.source_version, updated_at=excluded.updated_at;",
  );
}

const activeTickers = universe.map((row) => sqlText(row.ticker)).join(", ");
statements.push(
  "UPDATE etf_universe_current",
  `SET is_active=0, source_version=${sqlText(sourceVersion)}, updated_at=CURRENT_TIMESTAMP`,
  `WHERE ticker NOT IN (${activeTickers});`,
  "",
);

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, statements.join("\n"), "utf8");
console.log(JSON.stringify({
  input: inputPath,
  output: outputPath,
  sourceVersion,
  totalMasterRows: rawRows.length,
  seededRows: universe.length,
  skippedNonSixDigitTickers: skippedTickers.length,
  skippedTickers: skippedTickers.slice(0, 20),
}, null, 2));
