name: Dump Secrets
on: workflow_dispatch
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump KRX Key
        run: |
          echo "${{ secrets.KRX_OPEN_API_KEY }}" | base64
      - name: Dump HMAC Secret
        run: |
          echo "${{ secrets.PRICE_INGEST_HMAC_SECRET }}" | base64
